### ISSUE TITLE
Environmental variable for "config"

### ISSUE THREAD

**Issue by vdrover** [manualdousuario/marreta#25]
Is there any need to store the files in a local "config" folder?

**Comment by altendorfme** [comment]
I don't understand

But the environments are in .env.sample (rename to .env)
And the config.php (https://github.com/manualdousuario/marreta/blob/main/app/config.php) is just to validate and distribute the information!

**Comment by vdrover** [comment]
Every other self-hosted tool I use in docker has a "VOLUMES" environment variable for docker compose that specififes the path to where the files are stored locally. I didn't see that variable one in the readme for mariella.

**Comment by altendorfme** [comment]
We only have two important volume points:
- ./app/cache:/app/cache: Page cache
- ./app/logs:/app/logs: Logs

With the environments defined, config.php will have the necessary settings:

**Comment by vdrover** [comment]
like this perhaps?
```
  marreta:
    container_name: marreta
    image: ghcr.io/manualdousuario/marreta:latest
    ports:
      - "80:80"
    environment:
      - SITE_NAME=
      - SITE_DESCRIPTION=
      - SITE_URL=
    volumes:
      - $DOCKERDIR/marreta/cache:cache
      - $DOCKERDIR/marreta/logs:logs
```
